/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChampionImg: typeof import('./src/components/img/championImg.vue')['default']
    ConnectStatus: typeof import('./src/components/ConnectStatus.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GameDetailInfo: typeof import('./src/components/GameDetailInfo.vue')['default']
    GameInfo: typeof import('./src/components/GameInfo.vue')['default']
    GameInfoList: typeof import('./src/components/GameInfoList.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar.vue')['default']
    Index: typeof import('./src/components/Index.vue')['default']
    ItemImg: typeof import('./src/components/img/itemImg.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    PerkImg: typeof import('./src/components/img/perkImg.vue')['default']
    PlayerGameInfo: typeof import('./src/components/PlayerGameInfo.vue')['default']
    Plugs: typeof import('./src/components/img/plugs.vue')['default']
    PositionImg: typeof import('./src/components/img/positionImg.vue')['default']
    ProfileImg: typeof import('./src/components/img/profileImg.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuneImg: typeof import('./src/components/img/runeImg.vue')['default']
    SpellImg: typeof import('./src/components/img/spellImg.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
