/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChampionImg: (typeof import("./src/components/img/championImg.vue"))["default"];
    ConnectStatus: (typeof import("./src/components/ConnectStatus.vue"))["default"];
    EpicLoading: (typeof import("./src/components/EpicLoading.vue"))["default"];
    Footer: (typeof import("./src/components/Footer.vue"))["default"];
    GameDetailInfo: (typeof import("./src/components/GameDetailInfo.vue"))["default"];
    GameInfo: (typeof import("./src/components/GameInfo.vue"))["default"];
    GameInfoList: (typeof import("./src/components/GameInfoList.vue"))["default"];
    HeaderBar: (typeof import("./src/components/HeaderBar.vue"))["default"];
    Index: (typeof import("./src/components/Index.vue"))["default"];
    ItemImg: (typeof import("./src/components/img/itemImg.vue"))["default"];
    LeagueOfLeagendsLoading: (typeof import("./src/components/loading/LeagueOfLeagendsLoading.vue"))["default"];
    Logo: (typeof import("./src/components/Logo.vue"))["default"];
    Nav: (typeof import("./src/components/Nav.vue"))["default"];
    NAvatar: (typeof import("naive-ui"))["NAvatar"];
    NButton: (typeof import("naive-ui"))["NButton"];
    NCard: (typeof import("naive-ui"))["NCard"];
    NCheckbox: (typeof import("naive-ui"))["NCheckbox"];
    NConfigProvider: (typeof import("naive-ui"))["NConfigProvider"];
    NDivider: (typeof import("naive-ui"))["NDivider"];
    NDrawer: (typeof import("naive-ui"))["NDrawer"];
    NDrawerContent: (typeof import("naive-ui"))["NDrawerContent"];
    NGlobalStyle: (typeof import("naive-ui"))["NGlobalStyle"];
    NInput: (typeof import("naive-ui"))["NInput"];
    NInputGroup: (typeof import("naive-ui"))["NInputGroup"];
    NMessageProvider: (typeof import("naive-ui"))["NMessageProvider"];
    NModal: (typeof import("naive-ui"))["NModal"];
    NPageHeader: (typeof import("naive-ui"))["NPageHeader"];
    NPagination: (typeof import("naive-ui"))["NPagination"];
    NPopconfirm: (typeof import("naive-ui"))["NPopconfirm"];
    NRadio: (typeof import("naive-ui"))["NRadio"];
    NRadioGroup: (typeof import("naive-ui"))["NRadioGroup"];
    NSelect: (typeof import("naive-ui"))["NSelect"];
    NSlider: (typeof import("naive-ui"))["NSlider"];
    NSpace: (typeof import("naive-ui"))["NSpace"];
    NSpin: (typeof import("naive-ui"))["NSpin"];
    NSwitch: (typeof import("naive-ui"))["NSwitch"];
    NTab: (typeof import("naive-ui"))["NTab"];
    NTabs: (typeof import("naive-ui"))["NTabs"];
    NTag: (typeof import("naive-ui"))["NTag"];
    NTooltip: (typeof import("naive-ui"))["NTooltip"];
    PerkImg: (typeof import("./src/components/img/perkImg.vue"))["default"];
    PlayerGameInfo: (typeof import("./src/components/PlayerGameInfo.vue"))["default"];
    Plugs: (typeof import("./src/components/img/plugs.vue"))["default"];
    PositionImg: (typeof import("./src/components/img/positionImg.vue"))["default"];
    ProfileImg: (typeof import("./src/components/img/profileImg.vue"))["default"];
    RouterLink: (typeof import("vue-router"))["RouterLink"];
    RouterView: (typeof import("vue-router"))["RouterView"];
    RuneImg: (typeof import("./src/components/img/runeImg.vue"))["default"];
    SpellImg: (typeof import("./src/components/img/spellImg.vue"))["default"];
  }
}
