export const lcuConst = {
  connected: "lcu:connected",
  connecting: "lcu:connecting",
  disconnect: "lcu:disconnect",
  gameFlowPhase: "lcu:gameFlowPhase",
  champSelect: "lcu:champSelect",
  getCurrentSummoner: "lcu:getCurrentSummoner",
  queryGameDetails: "lcu:queryGameDetails",
  queryMatchHistory: "lcu:queryMatchHistory",
  killRender: "lcu:killRender",
  queryConnectStatus: "lcu:queryConnectStatus",
  getSummonerByName: "lcu:getSummonerByName",
  getSummonerByPuuid: "lcu:getSummonerByPuuid",
  getCustomRunes: "lcu:getCustomRunes",
  getOPGGRunes: "lcu:getOPGGRunes",
  applyRune: "lcu:applyRune",
};
